
const ACTION_TYPES = {
 LOGIN                  : 'LOGIN',
 GET_USER_DETAILS : 'GET_USER_DETAILS',
 GET_PROVIDERS : 'GET_PROVIDERS',
 GET_VMS_FOR_PROVIDER : 'GET_VMS_FOR_PROVIDER',
 GET_ALL_NOTIFICATIONS : 'GET_ALL_NOTIFICATIONS',
}

export default ACTION_TYPES